# Generated by Django 4.2 on 2025-01-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(default='https://res.cloudinary.com/dwxzdd3bf/image/upload/v1733151833/media/images/book-front-page_w2impn.webp', upload_to='images/'),
        ),
    ]
