# Generated by Django 4.2 on 2025-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(default='media/images/books-1246674_1280_ksuj7m', upload_to='images/'),
        ),
    ]
