# Generated by Django 4.2 on 2025-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmailapp', '0002_alter_emailmodel_show_alternativ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='show_alternativ',
            field=models.CharField(choices=[('books', 'Books'), ('jobs', 'Jobs'), ('reviews', 'Reviews'), ('other', 'Other')]),
        ),
    ]
